apiVersion: v1
kind: Service
metadata:
ear name: esp-echo
spec:
  ports:
  - port: 80
    targetPort: 8081
    protocol: TCP
    name: http
  selector:
    app: esp-echo
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: esp-echo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: esp-echo
    spec:
      containers:
      # [START esp]
      - name: esp
        image: gcr.io/endpoints-release/endpoints-runtime:1
        args: [
          "--http_port=8081",
          "--backend=127.0.0.1:8080",
          "--service=echo-api.endpoints.test-1-179209.cloud.goog",
          "--rollout_strategy=managed",
        ]
      # [END esp]
        ports:
        - containerPort: 8081
      - name: echo
        image: gcr.io/test-1-179209/k8endpoint@sha256:ad90483d058e93ba0bf6ae7b70c3592bde859dd2db63781d05a3a005e36c73ea
        ports:
        - containerPort: 8080
