swagger: "2.0"
info:
  title: "k8 with endpoints-v1"
  description: "k8endpoint-v1"
  version: "1.0.0"
host: "echo-api.endpoints.test-1-179209.cloud.goog"
schemes:
  - "https"
paths:
  "/employee":
    get:
      description: "Get the employee name."
      operationId: "employee"
      parameters:
        -
          name: employee
          in: path
          required: true
          type: string
      responses:
        200:
          description: "Success."
          schema:
            type: string
        400:
          description: "Invalid path."

  "/city":
    get:
      description: "Get the city name."
      operationId: "citydata"
      parameters:
        -
          name: city
          in: path
          required: true
          type: string
      responses:
        200:
          description: "Success."
          schema:
            type: string
        400:
          description: "Invalid path."







